name: Generate Snake Game

on:
  schedule:
    - cron: "0 */12 * * *" # a cada 12h
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest
    steps:
      # Baixa o repositório
      - uses: actions/checkout@v3

      # Gera o SVG
      - uses: Platane/snk@v3
        with:
          github_user_name: NicolasRibe
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Publica no branch output
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
